# codemagic.yaml
# This workflow builds your Cordova app for Android.
workflows:
  android-debug-build:
    name: Construir APK de Teste v2
    environment:
      # Use a recent Node.js version
      node: 20.x
      # Define Java version for Android builds
      java: 17
    scripts:
      - name: Instalar a CLI do Cordova
        script: |
          npm install -g cordova
      - name: Instalar dependências do projeto
        script: |
          npm install
      - name: Adicionar plataforma Android (usando a versão do package.json)
        script: |
          cordova platform add android
      - name: Construir o APK de teste (Debug)
        script: |
          cordova build android --debug
    artifacts:
      # Caminho corrigido para o APK gerado
      - platforms/android/app/build/outputs/apk/debug/app-debug.apk